---
# This workflow is reusable and starts all tests

name: Create and Append Release Assets

on:
  workflow_call:


jobs:
  create_distributions:
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: True
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: create Distribution files
        uses: ./.github/workflows/reusable-create-distribution-files.yml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: True
          draft: True
          files: dist/*.zip