name: Create Distribution Files

on:
  workflow_call:

jobs:
  create_distributions:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check-out Build repository
        uses: actions/checkout@v2
        with:
          repository: platomo/platomo-build
          token: ${{ secrets.PLATOMO_BUILDER_ACCESS }}
          path: zipper

      - name: Run Build
        run:  |
              pip install -r requirements-dev.txt
              python ./zipper/build.py 
