---
# This workflow is reusable and starts all tests

name: Reusable workflow to run Python tests

on:
  workflow_call:
    inputs:
      py-version:
        required: true
        type: string
      os:
        required: true
        type: string
      test_path:
        required: true
        type: string
      ffmpeg-required:
        default: false
        type: boolean

jobs:
  test:
    name: Running tests on ${{ inputs.os }} with Python ${{ inputs.py-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run ffmpeg
        if: ffmpeg-required
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: Set up Python ${{ inputs.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.py-version }}
          cache: 'pip'
      - name: Install Python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
          fi
          if [ -f "requirements-dev.txt" ]; then
              pip install -r requirements-dev.txt
          fi

      - name: Lint
        run: |
          flake8 .
      - name: Static type checking
        run: |
          mypy .
      - name: Run pytest
        run: pytest --cov=${{ inputs.test_path }} tests/
