name: Reusable workflow to create release and append assets 

on:
  workflow_call:
    inputs:
      package-version:
        required: true
        type: string
      draft-release:
        required: true
        type: boolean
      pre-release:
        required: true
        type: boolean
    secrets:
      PLATOMO_BUILDER_ACCESS:
        required: true

jobs:
  release:
    name: Release version ${{ inputs.package-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3
      - name: Check-out platomo-build repository
        uses: actions/checkout@v3
        with:
          repository: platomo/platomo-build
          token: ${{ secrets.PLATOMO_BUILDER_ACCESS }}
          path: platomo-build

      - name: Install builder dependencies
        run: |
          cd platomo-build
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
          fi
          if [ -f "requirements-dev.txt" ]; then
              pip install -r requirements-dev.txt
          fi

      - name: Build release assets
        run : python ./platomo-build/build.py --package_version ${{ inputs.package-version }}

      - name: Delete existing release assets
        run:  gh release delete-assets ${{ inputs.package-version }}

      - name: Release and append assets
        uses: softprops/action-gh-release@v1
        with:
          generate-release-notes: True
          tag_name: ${{ inputs.package-version }}
          draft: ${{ inputs.draft-release }}
          prerelease: ${{ inputs.pre-release }}
          append_body: false
          files: dist/*
