---
# This workflow is reusable and starts all tests

name: Run Python Tests

on:
  workflow_call:
    inputs:
      py-version:
        required: true
        type: string
      os:
        required: true
        type: string
      test_path:
        required: true
        type: string

jobs:
  test:
    name: Running test on ${{ inputs.os }} with Python ${{ inputs.py-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.py-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint codebase
        run: |
          flake8 .
      - name: Execute static type checking
        run: |
          mypy .
      - name: Test with pytest
        run: pytest --cov=${{ inputs.test_path }} tests/