  on:
    workflow_call:
        inputs:
            package-version:
                required: true
                type: string
            os:
                required: true
                type: string
  jobs:
    update_version:
        name: update the version.py
        runs-on: ${{ input.os }}
        steps:
            - uses: actions/checkout@v4
            - name: change version.py
              run:
                  if [ ${{ inputs.package-version }} == 'nightly' ]; then
                    dt=$(date '+%Y%m%d %H%M%S');
                    sed -i "__version__= ${dt}"
                  else
                    sed -i "__version__= ${inputs.package-version}"

