name: Reusable workflow to create and publish pypi release


on:
  workflow_call:
    inputs:
      release_url:
        required: true
        type: string
      os:
        required: true
        type: string
      py-version:
        required: true
        type: string
      package_version:
        required: true
        type: string
    secrets:
      PLATOMO_BUILDER_ACCESS:
        required: true

jobs:
  build-n-publish:
    name: Build and upload release to TestPyPI
    runs-on: ${{ input.os }}
    strategy:
      fail-fast: True
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    environment:
      name: testpypi
      url: inputs.release_url
    permissions:
      actions: read
      contents: read
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Check-out platomo-build repository
        uses: actions/checkout@v4
        with:
          repository: platomo/platomo-build
          token: ${{ secrets.PLATOMO_BUILDER_ACCESS }}
          path: platomo-build
      - name: Install builder dependencies
        run: |
          cd platomo-build
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
          fi
          if [ -f "requirements-dev.txt" ]; then
              pip install -r requirements-dev.txt
          fi
      - name: Build release assets
        run: python ./platomo-build/build.py --inputs.package_version
      - name: Display dist content
        run: ls -ahl dist/
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: dist/
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Show dist content
        run: ls -ahl dist/
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true